refactor(ps1): clean rc before install

diff --git a/lib/ps1/src/install b/lib/ps1/src/install
--- a/lib/ps1/src/install
+++ b/lib/ps1/src/install
@@ -1,43 +1,44 @@
 #!/usr/bin/env bash
 
+info() { printf '\033[34m[%-5s] %s\033[0m\n' 'INFO' "$*" >&2; }
+error() { printf '\033[31m[%-5s] %s\033[0m\n' 'ERROR' "$*" >&2; }
+
 if [ "$(id -u)" != '0' ]; then
-    printf '\033[31m[%-5s] %s\033[0m\n' \
-        'ERROR' 'Installer requires root privileges' >&2
+    error 'Installer requires root privileges' >&2
     exit 1
 fi
 
+set -eo pipefail
+
 pwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 install_dir='/usr/local/libexec/ps1'
-printf '\033[34m[%-5s] %s\033[0m\n' 'INFO' "Installing to '$install_dir'"
+info "Installing to '$install_dir'"
 
 mkdir -p "$install_dir" || {
-    printf '\033[31m[%-5s] %s\033[0m\n' \
-        'ERROR' "Failed to create directory '$install_dir'" >&2
+    error "Failed to create directory '$install_dir'"
     exit 1
 }
 
 chmod 755 "$install_dir" || {
-    printf '\033[31m[%-5s] %s\033[0m\n' \
-        'ERROR' "Failed to set permissions for '$install_dir'" >&2
+    error "Failed to set permissions for '$install_dir'"
     exit 1
 }
 
 for f in "$pwd"/scripts/*; do
     cp -r "$f" "$install_dir" || {
-        printf '\033[31m[%-5s] %s\033[0m\n' \
-            'ERROR' "Failed to copy '${f##*/}' to '$install_dir'" >&2
+        error "Failed to copy '${f##*/}' to '$install_dir'"
         exit 1
     }
     chmod 755 "${install_dir}/${f##*/}" || {
-        printf '\033[31m[%-5s] %s\033[0m\n' \
-            'ERROR' "Failed to set executable permissions for '${install_dir}/${f##*/}'" >&2
+        error "Failed to set executable permissions for '${install_dir}/${f##*/}'"
         exit 1
     }
 done
 
-printf '\033[34m[%-5s] %s\033[0m\n' \
-    'INFO' "Linking 'get-ps1' to '/usr/local/bin/get-ps1'"
-ln -s "${install_dir}/get-ps1" '/usr/local/bin/get-ps1'
+ln -s "${install_dir}/get-ps1" '/usr/local/bin/get-ps1' || {
+    error "Failed to link '${install_dir}/get-ps1' to '/usr/local/bin/get-ps1'"
+    exit 1
+}
 
 target_user="$SUDO_USER"
 [ -z "$target_user" ] \
@@ -48,27 +49,31 @@ is_root='false'
     && is_root='true'
 
 home="$(sudo -u "$target_user" bash -c 'echo $HOME')"
+
+info "Cleaning shell runtime configs"
+for sh in bash zsh; do
+    sed -i '/<(get-ps1.*)$/d' "${home}/.${sh}rc" || true
+    [ "$is_root" = 'false' ] \
+        && sed -i '/<(get-ps1.*)$/d' ~/."${sh}rc" || true
+done
+
 if command -v zsh &> /dev/null; then
-    printf '\033[34m[%-5s] %s\033[0m\n' \
-        'INFO' 'Zshell found, installing to .zshrc'
+    info 'Zsh found, installing to ~/.zshrc'
     echo 'source <(get-ps1 zsh)' | sudo -u "$target_user" tee -a "$home"/.zshrc 1> /dev/null || {
-        printf '\033[31m[%-5s] %s\033[0m\n' \
-            'ERROR' "Failed to set PS1 in '${home}/.zshrc'" >&2
+        error "Failed to set PS1 in '${home}/.zshrc'"
         exit 1
     }
     [ "$is_root" = 'false' ] \
         && echo 'source <(get-ps1 zsh)' >> ~/.zshrc
 fi
 
-printf '\033[34m[%-5s] %s\033[0m\n' 'INFO' 'Installing to .bashrc'
+info 'Installing to .bashrc'
 echo 'source <(get-ps1 bash)' | sudo -u "$target_user" tee -a "$home"/.bashrc 1> /dev/null || {
-    printf '\033[31m[%-5s] %s\033[0m\n' \
-        'ERROR' "Failed to set PS1 in '${home}/.bashrc'" >&2
+    error "Failed to set PS1 in '${home}/.bashrc'"
     exit 1
 }
 [ "$is_root" = 'false' ] \
     && echo 'source <(get-ps1 bash)' >> ~/.bashrc
 
 printf '\033[32m[%-5s] %s\033[0m\n' 'OK' 'All done :)'
-
-exit 0
+info 'Install complete'
